# Generated by Django 6.0.1 on 2026-01-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reg', models.CharField(max_length=4, unique=True, verbose_name='Código de Registro')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('unidad_organica', models.CharField(max_length=150)),
                ('intendencia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoCharla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_charla', models.IntegerField()),
                ('titulo_charla', models.CharField(max_length=150)),
                ('asistio', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charlas', to='capacitaciones.empleado')),
            ],
        ),
    ]
