# Generated by Django 6.0.1 on 2026-01-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_perfiladmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharlaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de Charla')),
                ('titulo', models.CharField(max_length=255)),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='Link del Video')),
                ('url_evaluacion', models.URLField(blank=True, null=True, verbose_name='Link de Evaluación')),
            ],
        ),
        migrations.RemoveField(
            model_name='progresocharla',
            name='numero_charla',
        ),
        migrations.RemoveField(
            model_name='progresocharla',
            name='titulo_charla',
        ),
        migrations.AlterField(
            model_name='progresocharla',
            name='resultado',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progresocharla',
            name='charla_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.charlamaestra'),
        ),
    ]
